### PR TITLE
enable GitHub Actions for CI

### PR DESCRIPTION
**Pull request by szabgab**
The tests now fail in the same way as they fail in #1

### CODE REVIEW

**Comment by neilb** [comment]
Thanks Gabor!

**Comment by neilb** [comment]
This resulted in [three failures](https://github.com/neilb/MooX-Role-CachedURL/actions/runs/3228679582).

**Comment by szabgab** [comment]
Yes, exactly the same way as the released version failed on my computer as reported in #1 that you have subsequently fixed and thus the CI jobs started to pass again.

**Comment by szabgab** [comment]
BTW the same issue was reported here as well: https://rt.cpan.org/Public/Bug/Display.html?id=144086

**Pull request merged**
